name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip3 install --user uv pytest pytest-cov
          make install

      - name: Run linter
      run: uv run python -m ruff check .

      - name: Run tests and generate coverage
        run: make test-coverage

      - name: Upload coverage to Qlty.sh
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: lcov.info  
